import { type Models } from 'node-appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts /home/arnab/Desktop/AppwriteOrm`.
 */

export type Users = Models.Document & {
  name: string | null;
  email: string | null;
  age: number | null;
  username: string | null;
  bio: string | null;
}

export type Products = Models.Document & {
  name: string | null;
  price: number | null;
  inStock: boolean | null;
  brand: string | null;
  category: string | null;
}

export type Posts = Models.Document & {
  title: string | null;
  content: string | null;
  likes: number | null;
  tags: string | null;
  published: boolean | null;
}

export type Events = Models.Document & {
  title: string | null;
  location: string | null;
  date: string | null;
  organizer: string | null;
  attendees: number | null;
}

export const models = {
  users: {} as Users,
  products: {} as Products,
  posts: {} as Posts,
  events: {} as Events,
};

